services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: product_aggregator_api_dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/product_aggregator?schema=public
      - API_KEY=${API_KEY}
      - AGGREGATOR_INTERVAL_MS=5000
      - STALE_THRESHOLD_MS=300000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    restart: unless-stopped
    command: npm run start:dev

  postgres:
    image: postgres:latest
    container_name: product_aggregator_db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_aggregator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
