version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_aggregator_api
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/product_aggregator?schema=public
      - API_KEY=${API_KEY}
      - AGGREGATOR_INTERVAL_MS=5000
      - STALE_THRESHOLD_MS=300000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: product_aggregator_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_aggregator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
